DCT-428: fall back to `fswatch` in docs/Makefile `watch` target

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -24,13 +24,31 @@ serve-up: serve-down
 serve-down:
 	docker rm --force $(NAME)
 
+WATCHES = ./dev ./src Dockerfile Makefile
+define WATCH
+  do clear \
+   ; date \
+   ; echo 'Re-rendering docs...' \
+   ; $(MAKE) -s build \
+   ; echo '...Done.' \
+   ; done
+endef
+
+.PHONY: watch-inotifywait
+watch-inotifywait:
+	@while inotifywait -e modify -r $(WATCHES); $(WATCH)
+
+.PHONY: watch-fswatch
+watch-fswatch:
+	@echo 'Watching for changes...'
+	@fswatch -ro --event Updated $(WATCHES) | while read x; $(WATCH)
+
 .PHONY: watch
 watch:
-	@command -v inotifywait >/dev/null \
-	  || (echo 'Unable to find `inotifywait`' && exit 1)
-	@while inotifywait -e modify -r ./dev ./src Dockerfile Makefile; \
-	  do clear \
-	   ; date \
-	   ; echo 'Re-rendering docs...' \
-	   ; $(MAKE) -s build \
-	   ; done
+	@if   command -v inotifywait >/dev/null; then \
+	   $(MAKE) -s watch-inotifywait; \
+	 elif command -v fswatch     >/dev/null; then \
+	   $(MAKE) -s watch-fswatch; \
+	 else \
+	   echo 'Unable to find `inotifywait` or `fswatch`.' && exit 1; \
+	 fi
